Update CI_cluster.yml

diff --git a/.github/workflows/CI_cluster.yml b/.github/workflows/CI_cluster.yml
--- a/.github/workflows/CI_cluster.yml
+++ b/.github/workflows/CI_cluster.yml
@@ -69,106 +69,127 @@ jobs:
         python setup.py bdist_wheel
         pip install dist/pyvearch*
 
-    # - name: Test Python SDK
-    #   run: |
-    #     cd sdk/python/test
-    #     pytest -x --log-cli-level=INFO
+    - name: Test Python SDK
+      run: |
+        cd sdk/python/test
+        pytest -x --log-cli-level=INFO
 
     - name: Install Docker Compose
       run: |
         sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
         sudo chmod +x /usr/local/bin/docker-compose
 
-    # - name: Run tests for master down and restart
-    #   run: |
-    #     cd cloud
-    #     docker-compose stop master1
-    #     cd ../test
-    #     pytest test_vearch.py -x -k "test_vearch_basic_usage" --log-cli-level=INFO
-    #     pytest test_cluster_master.py -x -k "TestClusterMasterPrepare" --log-cli-level=INFO
-    #     pytest test_cluster_master.py -x -k "TestClusterMasterOperate" --log-cli-level=INFO
-    #     # prepare for 2 masters down
-    #     pytest test_cluster_master.py -x -k "TestClusterMasterPrepare" --log-cli-level=INFO
-    #     cd ../cloud && docker-compose stop master2
-    #     cd ../test
-    #     pytest test_cluster_master.py -x -k "TestClusterMasterOperate" --log-cli-level=INFO
-    #     # all down
-    #     cd ../cloud && docker-compose stop master3
-    #     sleep 120
-    #     cd ../test
-    #     pytest test_cluster_master.py -x -k "TestClusterMasterOperate" --log-cli-level=INFO
-    #     cd ../cloud
-    #     docker-compose start master1 && sleep 30 && docker ps
-    #     docker-compose start master2 && sleep 30 && docker ps
-    #     docker-compose start master3 && sleep 90 && docker ps
-    #     cd ../test
-    #     pytest test_cluster_master.py -x -k "TestClusterMasterOperate" --log-cli-level=INFO
-    #     pytest test_vearch.py -x -k "test_vearch_basic_usage" --log-cli-level=INFO
-    #     curl -s -L -u root:secret http://127.0.0.1:8817/servers | jq
-    #     curl -s -L -u root:secret http://127.0.0.1:8817/cluster/health?detail=true | jq
+    - name: Run tests for master down and restart
+      run: |
+        cd cloud
+        docker-compose stop master1
+        cd ../test
+        pytest test_vearch.py -x -k "test_vearch_basic_usage" --log-cli-level=INFO
+        pytest test_cluster_master.py -x -k "TestClusterMasterPrepare" --log-cli-level=INFO
+        pytest test_cluster_master.py -x -k "TestClusterMasterOperate" --log-cli-level=INFO
+        # prepare for 2 masters down
+        pytest test_cluster_master.py -x -k "TestClusterMasterPrepare" --log-cli-level=INFO
+        cd ../cloud && docker-compose stop master2
+        cd ../test
+        pytest test_cluster_master.py -x -k "TestClusterMasterOperate" --log-cli-level=INFO
+        # all down
+        cd ../cloud && docker-compose stop master3
+        sleep 120
+        cd ../test
+        pytest test_cluster_master.py -x -k "TestClusterMasterOperate" --log-cli-level=INFO
+        cd ../cloud
+        docker-compose start master1 && sleep 30 && docker ps
+        docker-compose start master2 && sleep 30 && docker ps
+        docker-compose start master3 && sleep 90 && docker ps
+        cd ../test
+        pytest test_cluster_master.py -x -k "TestClusterMasterOperate" --log-cli-level=INFO
+        pytest test_vearch.py -x -k "test_vearch_basic_usage" --log-cli-level=INFO
+        curl -s -L -u root:secret http://127.0.0.1:8817/servers | jq
+        curl -s -L -u root:secret http://127.0.0.1:8817/cluster/health?detail=true | jq
 
-    # - name: Run tests for restart ps
-    #   run: |
-    #     cd test
-    #     pytest test_cluster_ps.py -k "TestClusterPartitionServerAdd" -x --log-cli-level=INFO
-    #     cd ../cloud
-    #     docker-compose stop ps1
-    #     sleep 30
-    #     docker-compose start ps1
-    #     cd ../test
-    #     pytest test_cluster_ps.py -x -k "TestClusterPartitionServerRecover" --log-cli-level=INFO
-    #     pytest test_cluster_ps.py -x -k "TestClusterPartitionServerCheckSpace" --log-cli-level=INFO
-    #     pytest test_cluster_ps.py -x -k "TestClusterPartitionServerDestroy" --log-cli-level=INFO
-    #     pytest test_cluster_ps.py -k "TestClusterPartitionChange" --log-cli-level=INFO
-    #     curl -s -L -u root:secret http://127.0.0.1:8817/servers | jq
-    #     curl -s -L -u root:secret http://127.0.0.1:8817/cluster/health?detail=true | jq
+    - name: Run tests for restart ps
+      run: |
+        cd test
+        pytest test_cluster_ps.py -k "TestClusterPartitionServerAdd" -x --log-cli-level=INFO
+        cd ../cloud
+        docker-compose stop ps1
+        sleep 30
+        docker-compose start ps1
+        cd ../test
+        pytest test_cluster_ps.py -x -k "TestClusterPartitionServerRecover" --log-cli-level=INFO
+        pytest test_cluster_ps.py -x -k "TestClusterPartitionServerCheckSpace" --log-cli-level=INFO
+        pytest test_cluster_ps.py -x -k "TestClusterPartitionServerDestroy" --log-cli-level=INFO
+        sleep 10
+        db_num=$(curl -s -L -u root:secret http://127.0.0.1:8817/dbs | jq '.data | length')
 
-    # - name: Run tests for faulty ps
-    #   run: |
-    #     cd test
-    #     pytest test_cluster_ps.py -x -k "TestClusterFaultyPartitionServerCreateSpace" --log-cli-level=INFO
-    #     pytest test_cluster_ps.py -x -k "TestClusterFaultyPartitionServerGetMetaData" --log-cli-level=INFO
-    #     cd ../cloud
-    #     docker-compose stop ps1
-    #     cd ../test
-    #     pytest test_cluster_ps.py -x -k "TestClusterFaultyPartitionServerPrepareData" --log-cli-level=INFO
-    #     pytest test_cluster_ps.py -x -k "TestClusterFaultyPartitionServerGetMetaData" --log-cli-level=INFO
-    #     cd ../cloud && docker-compose stop ps2
-    #     cd ../test
-    #     # TODO remove sleep
-    #     sleep 60
-    #     pytest test_cluster_ps.py -x -k "TestClusterFaultyPartitionServerSearch" --log-cli-level=INFO
-    #     pytest test_cluster_ps.py -x -k "TestClusterFaultyPartitionServerGetMetaData" --log-cli-level=INFO
-    #     cd ../cloud
-    #     docker-compose start ps1
-    #     docker-compose start ps2
-    #     sleep 60
-    #     cd ../test
-    #     pytest test_cluster_ps.py -x -k "TestClusterPartitionServerDestroy" --log-cli-level=INFO
-    #     curl -s -L -u root:secret http://127.0.0.1:8817/servers | jq
-    #     curl -s -L -u root:secret http://127.0.0.1:8817/cluster/health?detail=true | jq
+        if [ "$db_num" -ne 0 ]; then
+          echo "db is not empty"
+          exit 1
+        fi
+        pytest test_cluster_ps.py -k "TestClusterPartitionChange" --log-cli-level=INFO
+        curl -s -L -u root:secret http://127.0.0.1:8817/servers | jq
+        curl -s -L -u root:secret http://127.0.0.1:8817/cluster/health?detail=true | jq
 
-    # - name: Run tests for incomplete shared
-    #   run: |
-    #     cd test
-    #     pytest test_cluster_ps.py -x -k "TestIncompleteShardPrepare" --log-cli-level=INFO
-    #     cd ../cloud
-    #     docker-compose stop ps1
-    #     docker-compose stop ps2
-    #     cd ../test
-    #     # TODO remove sleep
-    #     sleep 60
-    #     pytest test_cluster_ps.py -x -k "TestIncompleteShardSearch" --log-cli-level=INFO
-    #     cd ../cloud
-    #     docker-compose stop ps3
-    #     docker-compose start ps1
-    #     docker-compose start ps2
-    #     docker-compose start ps3
-    #     sleep 60
-    #     cd ../test
-    #     pytest test_cluster_ps.py -x -k "TestClusterPartitionServerDestroy" --log-cli-level=INFO
-    #     curl -s -L -u root:secret http://127.0.0.1:8817/servers | jq
-    #     curl -s -L -u root:secret http://127.0.0.1:8817/cluster/health?detail=true | jq
+    - name: Run tests for faulty ps
+      run: |
+        cd test
+        pytest test_cluster_ps.py -x -k "TestClusterFaultyPartitionServerCreateSpace" --log-cli-level=INFO
+        pytest test_cluster_ps.py -x -k "TestClusterFaultyPartitionServerGetMetaData" --log-cli-level=INFO
+        cd ../cloud
+        docker-compose stop ps1
+        cd ../test
+        pytest test_cluster_ps.py -x -k "TestClusterFaultyPartitionServerPrepareData" --log-cli-level=INFO
+        pytest test_cluster_ps.py -x -k "TestClusterFaultyPartitionServerGetMetaData" --log-cli-level=INFO
+        cd ../cloud && docker-compose stop ps2
+        cd ../test
+        # TODO remove sleep
+        sleep 60
+        pytest test_cluster_ps.py -x -k "TestClusterFaultyPartitionServerSearch" --log-cli-level=INFO
+        pytest test_cluster_ps.py -x -k "TestClusterFaultyPartitionServerGetMetaData" --log-cli-level=INFO
+        cd ../cloud
+        docker-compose start ps1
+        docker-compose start ps2
+        sleep 60
+        cd ../test
+        pytest test_cluster_ps.py -x -k "TestClusterPartitionServerDestroy" --log-cli-level=INFO
+        sleep 10
+        db_num=$(curl -s -L -u root:secret http://127.0.0.1:8817/dbs | jq '.data | length')
+
+        if [ "$db_num" -ne 0 ]; then
+          echo "db is not empty"
+          exit 1
+        fi
+        curl -s -L -u root:secret http://127.0.0.1:8817/servers | jq
+        curl -s -L -u root:secret http://127.0.0.1:8817/cluster/health?detail=true | jq
+
+    - name: Run tests for incomplete shared
+      run: |
+        cd test
+        pytest test_cluster_ps.py -x -k "TestIncompleteShardPrepare" --log-cli-level=INFO
+        cd ../cloud
+        docker-compose stop ps1
+        docker-compose stop ps2
+        cd ../test
+        # TODO remove sleep
+        sleep 60
+        pytest test_cluster_ps.py -x -k "TestIncompleteShardSearch" --log-cli-level=INFO
+        cd ../cloud
+        docker-compose stop ps3
+        docker-compose start ps1
+        docker-compose start ps2
+        docker-compose start ps3
+        sleep 60
+        cd ../test
+        pytest test_cluster_ps.py -x -k "TestClusterPartitionServerDestroy" --log-cli-level=INFO
+        sleep 10
+        db_num=$(curl -s -L -u root:secret http://127.0.0.1:8817/dbs | jq '.data | length')
+
+        if [ "$db_num" -ne 0 ]; then
+          echo "db is not empty"
+          exit 1
+        fi
+        curl -s -L -u root:secret http://127.0.0.1:8817/servers | jq
+        curl -s -L -u root:secret http://127.0.0.1:8817/cluster/health?detail=true | jq
 
     - name: Run tests for fail server
       run: |
@@ -220,73 +241,87 @@ jobs:
         docker-compose -f cloud/docker-compose.yml restart ps1
         sleep 60
         cd test && pytest test_cluster_ps.py -x -k "TestClusterPartitionServerDestroy" --log-cli-level=INFO
+        sleep 10
+        db_num=$(curl -s -L -u root:secret http://127.0.0.1:8817/dbs | jq '.data | length')
+
+        if [ "$db_num" -ne 0 ]; then
+          echo "db is not empty"
+          exit 1
+        fi
         cd .. && docker-compose -f cloud/docker-compose.yml stop ps4
         sleep 30 && docker ps
         curl -s -L -u root:secret http://127.0.0.1:8817/servers | jq
         curl -s -L -u root:secret http://127.0.0.1:8817/cluster/health?detail=true | jq
 
-    # - name: Run tests for auto recover replica
-    #   run: |
-    #     cd test
-    #     pytest test_cluster_ps.py -x -k "TestFailServerPrepare" --log-cli-level=INFO
-    #     cd .. && docker-compose -f cloud/docker-compose.yml start ps4
-    #     docker-compose -f cloud/docker-compose.yml stop ps1
-    #     max_retries=30
-    #     retry=0
-    #     success=false
-    #     while [ $retry -lt $max_retries ]; do
-    #       servers=$(curl -s -L -u root:secret http://127.0.0.1:8817/servers)
-    #       status=$(echo $servers | jq -r '.data.servers[] | select(.server.ip == "172.16.238.19") | .partitions | length == 1')
-    #       if [ "$status" == "true" ]; then
-    #         success=true
-    #         echo $servers | jq
-    #         break
-    #       else
-    #         echo "Retry $((retry+1))/$max_retries: ps4 partitions num should be 1. Retrying in 30 seconds..."
-    #         echo $servers
-    #         retry=$((retry+1))
-    #         sleep 30
-    #       fi
-    #     done
-    #     if [ "$success" != "true" ]; then
-    #       echo "Error: ps4 partitions num should be 1 after $max_retries attempts."
-    #       exit 1
-    #     fi
+    - name: Run tests for auto recover replica
+      run: |
+        cd test
+        pytest test_cluster_ps.py -x -k "TestFailServerPrepare" --log-cli-level=INFO
+        cd .. && docker-compose -f cloud/docker-compose.yml start ps4
+        docker-compose -f cloud/docker-compose.yml stop ps1
+        max_retries=30
+        retry=0
+        success=false
+        while [ $retry -lt $max_retries ]; do
+          servers=$(curl -s -L -u root:secret http://127.0.0.1:8817/servers)
+          status=$(echo $servers | jq -r '.data.servers[] | select(.server.ip == "172.16.238.19") | .partitions | length == 1')
+          if [ "$status" == "true" ]; then
+            success=true
+            echo $servers | jq
+            break
+          else
+            echo "Retry $((retry+1))/$max_retries: ps4 partitions num should be 1. Retrying in 30 seconds..."
+            echo $servers
+            retry=$((retry+1))
+            sleep 30
+          fi
+        done
+        if [ "$success" != "true" ]; then
+          echo "Error: ps4 partitions num should be 1 after $max_retries attempts."
+          exit 1
+        fi
 
-    #     docker-compose -f cloud/docker-compose.yml start ps1
-    #     retry=0
-    #     success=false
-    #     while [ $retry -lt $max_retries ]; do
-    #       servers=$(curl -s -L -u root:secret http://127.0.0.1:8817/servers)
-    #       status=$(echo $servers | jq -r '.data.servers[] | select(.server.ip == "172.16.238.16") | .partitions | length == 0')
-    #       if [ "$status" == "true" ]; then
-    #         success=true
-    #         echo $servers | jq
-    #         break
-    #       else
-    #         echo "Retry $((retry+1))/$max_retries: ps1 partitions num should be 0. Retrying in 30 seconds..."
-    #         echo $servers
-    #         retry=$((retry+1))
-    #         sleep 30
-    #       fi
-    #     done
-    #     if [ "$success" != "true" ]; then
-    #       echo "Error: ps1 partitions num should be 0 after $max_retries attempts."
-    #       exit 1
-    #     fi
+        docker-compose -f cloud/docker-compose.yml start ps1
+        retry=0
+        success=false
+        while [ $retry -lt $max_retries ]; do
+          servers=$(curl -s -L -u root:secret http://127.0.0.1:8817/servers)
+          status=$(echo $servers | jq -r '.data.servers[] | select(.server.ip == "172.16.238.16") | .partitions | length == 0')
+          if [ "$status" == "true" ]; then
+            success=true
+            echo $servers | jq
+            break
+          else
+            echo "Retry $((retry+1))/$max_retries: ps1 partitions num should be 0. Retrying in 30 seconds..."
+            echo $servers
+            retry=$((retry+1))
+            sleep 30
+          fi
+        done
+        if [ "$success" != "true" ]; then
+          echo "Error: ps1 partitions num should be 0 after $max_retries attempts."
+          exit 1
+        fi
 
-    #     status=$(curl -u root:secret http://127.0.0.1:8817/cluster/health | jq -r '.data[0].spaces[0].status')
-    #     if [ "$status" != "green" ]; then
-    #       echo "Error: Status is not green. Status is $status."
-    #       exit 1
-    #     else
-    #       echo "Status is green."
-    #     fi
-    #     cd test && pytest test_cluster_ps.py -x -k "TestClusterPartitionServerDestroy" --log-cli-level=INFO
-    #     cd .. && docker-compose -f cloud/docker-compose.yml stop ps4
-    #     sleep 60 && docker ps
-    #     curl -s -L -u root:secret http://127.0.0.1:8817/servers | jq
-    #     curl -s -L -u root:secret http://127.0.0.1:8817/cluster/health?detail=true | jq
+        status=$(curl -u root:secret http://127.0.0.1:8817/cluster/health | jq -r '.data[0].spaces[0].status')
+        if [ "$status" != "green" ]; then
+          echo "Error: Status is not green. Status is $status."
+          exit 1
+        else
+          echo "Status is green."
+        fi
+        cd test && pytest test_cluster_ps.py -x -k "TestClusterPartitionServerDestroy" --log-cli-level=INFO
+        sleep 10
+        db_num=$(curl -s -L -u root:secret http://127.0.0.1:8817/dbs | jq '.data | length')
+
+        if [ "$db_num" -ne 0 ]; then
+          echo "db is not empty"
+          exit 1
+        fi
+        cd .. && docker-compose -f cloud/docker-compose.yml stop ps4
+        sleep 60 && docker ps
+        curl -s -L -u root:secret http://127.0.0.1:8817/servers | jq
+        curl -s -L -u root:secret http://127.0.0.1:8817/cluster/health?detail=true | jq
 
     - name: Run tests for replica anti_affinity strategy
       run: |
@@ -295,6 +330,7 @@ jobs:
         docker-compose -f cloud/docker-compose.yml start ps4
         docker-compose -f cloud/docker-compose.yml up ps5 -d
         while [ $anti_affinity -lt 4 ]; do
+          echo "replica_anti_affinity_strategy = $anti_affinity"
           sed -i "s/replica_anti_affinity_strategy = 0/replica_anti_affinity_strategy = $anti_affinity/" cloud/config_cluster.toml
 
           docker-compose -f cloud/docker-compose.yml restart master1
@@ -317,10 +353,23 @@ jobs:
             retry=$((retry+1))
             pytest test_cluster_ps.py -x -k "TestClusterPartitionServerDestroy" --log-cli-level=INFO
             sleep 5
+            db_num=$(curl -s -L -u root:secret http://127.0.0.1:8817/dbs | jq '.data | length')
+
+            if [ "$db_num" -ne 0 ]; then
+              echo "db is not empty"
+              exit 1
+            fi
           done
 
           pytest test_cluster_ps.py -x -k "TestFailAntiAffinity" --log-cli-level=INFO
           pytest test_cluster_ps.py -x -k "TestClusterPartitionServerDestroy" --log-cli-level=INFO
+          sleep 10
+          db_num=$(curl -s -L -u root:secret http://127.0.0.1:8817/dbs | jq '.data | length')
+
+          if [ "$db_num" -ne 0 ]; then
+            echo "db is not empty"
+            exit 1
+          fi
           
           cd ..
           sed -i "s/replica_anti_affinity_strategy = $anti_affinity/replica_anti_affinity_strategy = 0/" cloud/config_cluster.toml
